{"name": "Проверка неудачного обновления информации незалогиненного пользователя", "status": "passed", "description": "Проверка получения кода 401 Unauthorized и сообщения {\"success\": False, \"message\": \"You should be authorised\"} при отправке PATCH-запроса на обновление данных полей email, password, name незалогиненного пользователя", "parameters": [{"name": "update_field", "value": "'name'"}, {"name": "new_value", "value": "'ivan'"}], "start": 1725094146360, "stop": 1725094146668, "uuid": "d595f7d8-a27d-4f7d-86ea-09a668fc10d7", "historyId": "46052d88ce836d62e165b5ee29a0020c", "testCaseId": "6e21411b351c557c0b49423acf5a1aed", "fullName": "tests.test_change_user_data.TestsChangeUserData#test_update_data_without_auth_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_user_data"}, {"name": "subSuite", "value": "TestsChangeUserData"}, {"name": "host", "value": "MAIBENBEN-PC"}, {"name": "thread", "value": "3736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_user_data"}]}